### ISSUE TITLE
SmsBroadcastReceiver a couple of questions.

### ISSUE THREAD

**Issue by orenben12** [JoaquimLey/sms-parsing#6]
Hi,

Nice example.  I've had a look as the sample, and noticed that smsMessage seems un-initialised.  Where should it be coming from?

`smsSender = smsMessage.getDisplayOriginatingAddress();`

How should it be populated?

Also SmsHelper.SERVICE_PROVIDER seems to be undeclared as well as listener.  Can you please give me guidance on where they should be coming from, please?

This would help compile build upon the example.

Many Thanks!

**Comment by pouyamiralayi** [comment]
@orenben12 

> Also SmsHelper.SERVICE_PROVIDER seems to be undeclared as well as listener.

i guess that ``ServiceProvider`` is the target number for the sms you want to catch.

the ``listener`` can be a final class in your activity that provides the event handling for you.

>  smsMessage seems un-initialised.

the correct code snippet is this:
```
                        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
                                smsSender = null;
				for (SmsMessage smsMessage : Telephony.Sms.Intents.getMessagesFromIntent(intent)) {
                                        if (smsSender == null) 
                                            smsSender = smsMessage.getDisplayOriginatingAddress();
					smsBody += smsMessage.getMessageBody();
				}
			} else {
```
cheers!

**Comment by orenben12** [comment]
Great thanks - I'll give it a try.
